PERGUNTAS = [
    "O que você faria se ganhasse na loteria?",
    "Para ser feliz só preciso de...",
    "Qual é a pior desculpa que você já deu para faltar ao escola?",
    "Se você pudesse criar uma lei maluca, qual seria?",
    "Qual seria o pior superpoder para se ter?",
    "Qual é a coisa mais estranha que você já comeu?",
    "Se você fosse presidente por um dia, qual seria sua primeira ação?",
    "Qual é a pior invenção de todos os tempos?",
    "Eu nunca vou entender por que as pessoas...",
    "Qual seria o pior lugar para um primeiro encontro?",
    "Qual é a melhor desculpa para terminar um namoro?",
    "Complete: O maior mistério da humanidade é...",
    "Se você pudesse mudar seu nome, qual escolheria e por quê?",
    "Qual é a pior música para tocar em um funeral?",
    "O segredo do sucesso é...",
    "Qual é a coisa mais embaraçosa que você faria por R$ 1 milhão?",
    "O conselho mais desencorajador para dar a uma criança.",
    "Qual seria o nome mais ridículo para um super-herói?",
    "Se você fosse um objeto inanimado, qual seria e por quê?",
    "Qual é a pior coisa que você pode dizer em um primeiro encontro?",
    "Se sua vida fosse um filme, qual seria o título?",
    "Qual é a pior coisa que você pode encontrar na sua comida?",
    "Se você pudesse trocar de vida com alguém por um dia, quem seria e o que faria?",
    "Qual é a coisa mais estranha que você já fez para impressionar alguém?",
    "Se você pudesse eliminar uma coisa do mundo, o que seria?",
    "Qual é a pior mentira que você já contou para sair de uma situação embaraçosa?",
    "Se você fosse um animal, qual seria e por quê?",
    "Qual é a coisa mais inútil que você já comprou?",
    "Se você pudesse ter qualquer trabalho no mundo, qual seria e por quê?",
    "Qual é a pior coisa que você já fez em público?",
    "Se você pudesse ser um personagem de desenho animado, qual seria?",
    "Qual é a coisa mais estranha que você já viu alguém fazer em público?",
    "Se você pudesse trocar de lugar com alguém famoso por um dia, quem seria e o que faria?",
    "Qual é a pior coisa que você já disse para alguém sem querer?",
    "Se você pudesse ter qualquer habilidade inútil, qual seria?",
    "Qual é a coisa mais embaraçosa que você já fez na frente de uma pessoa que gosta?",
    "Se você pudesse ser um vilão de filme, qual seria e por quê?",
] 